language: python
python: 2.7
env:
  - TOX_ENV=pep8
  - TOX_ENV=pypy
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py27_coverage
install:
  - pip install --upgrade pip setuptools tox virtualenv
script: 
  - tox -v -v -e $TOX_ENV
after_success:  
  - coveralls    