language: python
python: 2.7
env:
  - TOX_ENV=pep8
  - TOX_ENV=pypy
  - TOX_ENV=py26
  - TOX_ENV=py27
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq which
install:
  - pip install --upgrade pip setuptools tox virtualenv
script: 
  - tox -v -v -e $TOX_ENV
after_success:  
  - coveralls    